import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TheGenius
 */
public class login extends javax.swing.JFrame {

private final String url =
    "jdbc:sqlserver://localhost:1433;" +
     "databaseName=HospitalManagement;integratedSecurity=true;" +
     "encrypt=true;trustServerCertificate=true";
    public login() {
        initComponents();
        loadjdbc.init();
    }
public boolean checkAdmin(String username,String password){

    
        boolean flag=false;
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;
        
        try
        {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "SELECT * FROM Admin where username='"+username+"' "
                    + "and Password='"+password+"'";
            result = stmt.executeQuery(query);
            if(result.next())
            {
                new home().setVisible(true);
                flag=true;
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Username or password");
            }
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        finally
        {
           if(con != null){ try{ con.close();} catch(Exception ex){}}
           if(stmt != null){ try{ stmt.close();} catch(Exception ex){}}
           if(result != null){ try{ result.close();} catch(Exception ex){}}

return flag;
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usertextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 88, 23));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 89, -1));

        usertextField.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        usertextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usertextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 340, -1));

        passwordTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 340, -1));

        loginButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 110, 30));

        closeButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross.png"))); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/—Pngtree—blue hospital medical western medicine_954226.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -390, 790, 1100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null, "Do you want to Close the App","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        } 
       
    }//GEN-LAST:event_closeButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
        String username =usertextField.getText();
        String password =passwordTextField.getText();
        
        
         if(username.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please , Enter your username");
            return;
        }
        if(password.isEmpty())
        {
           JOptionPane.showMessageDialog(this,"Please , Enter your password");
           return; 
        }
        checkAdmin(username, password);
       
        
    
//        if(usertextField.getText().equals("rafek")&&passwordTextField.getText().equals("admin")){
//            setVisible(false);
//            new home().setVisible(true);
//        }else{
//        JOptionPane.showMessageDialog(null , "incorrect Username & Password");
//        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usertextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField usertextField;
    // End of variables declaration//GEN-END:variables
}
